
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Martin Hara
 */
public class aplikasimencatatpesanan extends javax.swing.JFrame {

    /**
     * Creates new form aplikasimencatatpesanan
     */
    public aplikasimencatatpesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmbkopi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        namapel = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        namapelanggan = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        jumlah = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jmlpesanan = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Kopipel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        finaltotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Selesai = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("SELAMAT DATANG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("KOPI JAVVA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel4.setText(" Javva: Setiap Terasa adalah Petualangan Rasa.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, 20));

        jLabel3.setText("Jl. Raya Telang,PO BOX 02 Kecamatan Kamal, Bangkalan Jawa Timur 69162");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Coffee.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Jenis Kopi          :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        cmbkopi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmbkopi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arrabica Coffee", "Robusta Coffee", "Liberian Coffee", "Excelsa Coffee" }));
        jPanel2.add(cmbkopi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 128, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin Hara\\Downloads\\anon.gif")); // NOI18N
        jLabel6.setText(" ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 110, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Jhon Javva Lennon");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel8.setText("      Barista at Javva Coffe");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 132, -1));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 181, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("Nama Pelanggan :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 94, -1));
        jPanel2.add(namapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 128, -1));

        jLabel11.setText("========================================================================================");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 720, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Data Pembelian");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 292, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setText("Nama Pelanggan :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 317, -1, -1));
        jPanel2.add(namapelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 317, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setText("Harga                  :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 338, 93, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setText("Jumlah Item        :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 361, -1, -1));
        jPanel2.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 338, 52, 17));
        jPanel2.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 361, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setText("Jumlah Pesanan  :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));
        jPanel2.add(jmlpesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 128, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel17.setText("Kopi                   : ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 382, -1, -1));
        jPanel2.add(Kopipel, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 382, -1, -1));

        jLabel18.setText("Total : ");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 438, -1, -1));
        jPanel2.add(finaltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 438, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin Hara\\Downloads\\Reset.png")); // NOI18N
        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, -1));

        Selesai.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin Hara\\Downloads\\Save_1.png")); // NOI18N
        Selesai.setText("Selesai");
        Selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelesaiActionPerformed(evt);
            }
        });
        jPanel2.add(Selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 480, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin Hara\\Downloads\\Shutdown.png")); // NOI18N
        jButton2.setText("Keluar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 480, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin Hara\\Downloads\\coffee JAVVA (1).png")); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 870, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelesaiActionPerformed
        // TODO add your handling code here:
         String fnama = namapel.getText();
         String fjmlpesanan = jmlpesanan.getText();
         
         namapelanggan.setText(""+fnama);
         String selectedOptionskopi = (String) cmbkopi.getSelectedItem();
         if (cmbkopi.getSelectedIndex() == 0) {
        // Logika jika indeks 0 (item pertama) dipilih
        Kopipel.setText(""+selectedOptionskopi);
        int ind0=4000;
        jumlah.setText(""+fjmlpesanan);
        harga.setText(""+ind0);
        int total=ind0*Integer.parseInt(fjmlpesanan);
        Integer.valueOf(total);
        finaltotal.setText(""+total);
         }
         if (cmbkopi.getSelectedIndex() == 1) {
        // Logika jika indeks 0 (item pertama) dipilih
        Kopipel.setText(""+selectedOptionskopi);
        int ind1=8000;
        jumlah.setText(""+fjmlpesanan);
        harga.setText(""+ind1);
        int total=ind1*Integer.parseInt(fjmlpesanan);
        Integer.valueOf(total);
          finaltotal.setText(""+total);
         }
         if (cmbkopi.getSelectedIndex() == 2) {
        // Logika jika indeks 0 (item pertama) dipilih
        Kopipel.setText(""+selectedOptionskopi);
        int ind2=14000;
        jumlah.setText(""+fjmlpesanan);
        harga.setText(""+ind2);
        int total=ind2*Integer.parseInt(fjmlpesanan);
        Integer.valueOf(total);
          finaltotal.setText(""+total);
         }
         if (cmbkopi.getSelectedIndex() == 3) {
        // Logika jika indeks 0 (item pertama) dipilih
        Kopipel.setText(""+selectedOptionskopi);
        
        int ind3=16000;
        harga.setText(""+ind3);
        jumlah.setText(""+fjmlpesanan);
        int total=ind3*Integer.parseInt(fjmlpesanan);
        Integer.valueOf(total);
          finaltotal.setText(""+total);
         }
        
    }//GEN-LAST:event_SelesaiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         namapel.setText("");
         namapelanggan.setText("");
         jmlpesanan.setText("");
         cmbkopi.setSelectedIndex(0); 
         Kopipel.setText("");
         jumlah.setText("");
         harga.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin keluar dari aplikasi?",
                "Konfirmasi Keluar",
                JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            System.exit(0); // Menghentikan program secara normal
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aplikasimencatatpesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aplikasimencatatpesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aplikasimencatatpesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aplikasimencatatpesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aplikasimencatatpesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Kopipel;
    private javax.swing.JButton Selesai;
    private javax.swing.JComboBox<String> cmbkopi;
    private javax.swing.JLabel finaltotal;
    private javax.swing.JLabel harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jmlpesanan;
    private javax.swing.JLabel jumlah;
    private javax.swing.JTextField namapel;
    private javax.swing.JLabel namapelanggan;
    // End of variables declaration//GEN-END:variables
}
